version: "3.3"

services:
  db:
    image: backend/db
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - backend
    restart: on-failure
    env_file: .env
    ports:
      - "5431:5432"
    expose:
      - "5432"
    volumes:
      - "./pg_data:/var/lib/postgresql/data"

networks:
  backend:
